//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ManufacturerName { get; set; }
        public string Frequency { get; set; }
        public Nullable<int> ProductTypeCode { get; set; }
        public string RackID { get; set; }
    }
}
