//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItem
    {
        public int RecordID { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> ClientPrice { get; set; }
        public string UnitType { get; set; }
        public string ActionType { get; set; }
        public Nullable<int> RestOfAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
        public string RackId { get; set; }
        public string InvoiceNo { get; set; }
    }
}
